Layout/EndAlignment:
  EnforcedStyleAlignWith: variable
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/LineLength:
  Max: 132
Metrics/MethodLength:
  Severity: warning

Naming/FileName:
  Enabled: false

# Rationale: allow Weirich-style blocks
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/Alias:
  Enabled: false
