Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Metrics/LineLength:
  Max: 132
Metrics/MethodLength:
  Severity: warning

# Rationale: allow Weirich-style blocks
Style/BlockDelimiters:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/FileName:
  Enabled: false
Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Style/MultilineOperationIndentation:
  EnforcedStyle: indented
Style/RegexpLiteral:
  Enabled: false
Style/Alias:
  Enabled: false
Style/IndentArray:
  EnforcedStyle: consistent
